### ISSUE TITLE
error on charges

### ISSUE THREAD

**Issue by hizbullaharif** [stripe/stripe-node#1343]
onst charge = stripe.charges.create(
        {
          amount: product.price * 100,
          currency: 'usd',
          customer: customer.id,
          receipt_email: token.email,
          description: `Purchased the ${product.name}`,
          shipping: {
            name: token.card.name,
            address: {
              line1: token.card.address_line1,
              line2: token.card.address_line2,
              city: token.card.address_city,
              country: token.card.address_country,
              postal_code: token.card.address_zip,
            },
          },
        },
        {
          idempotencykey,
        },
      );

**_Error_**

Unknown arguments ([object Object]). Did you mean to pass an options object? See https://github.com/stripe/stripe-node/wiki/Passing-Options. (on API request to POST `/charges`)
    at getRequestOpts (D:\Dev beans\Stripe Integration\server\node_modules\stripe\lib\makeRequest.js:46:11)
    at D:\Dev beans\Stripe Integration\server\node_modules\stripe\lib\makeRequest.js:83:14
    at new Promise (<anonymous>)
    at makeRequest (D:\Dev beans\Stripe Integration\server\node_modules\stripe\lib\makeRequest.js:80:10)
    at Constructor.create (D:\Dev beans\Stripe Integration\server\node_modules\stripe\lib\StripeMethod.js:38:7)
    at StripeController.hello (D:\Dev beans\Stripe Integration\server\src\controllers\stripe.controller.ts:27:37)
    at invokeTargetMethod (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\invocation.ts:263:47)
    at D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\invocation.ts:240:12
    at transformValueOrPromise (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\value-promise.ts:298:12)
    at invokeTargetMethodWithInjection (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\invocation.ts:235:33)
    at InterceptedInvocationContext.invokeTargetMethod (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\invocation.ts:119:14)
    at targetMethodInvoker (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\interceptor.ts:349:23)
    at D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\interceptor-chain.ts:219:14
    at transformValueOrPromise (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\value-promise.ts:298:12)
    at GenericInterceptorChain.invokeNextInterceptor (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\interceptor-chain.ts:214:35)
    at GenericInterceptorChain.next (D:\Dev beans\Stripe Integration\server\node_modules\@loopback\context\src\interceptor-chain.ts:202:17)

**Comment by paulasjes-stripe** [comment]
The issues page for this repo is for problems with the library itself, whereas this is an integration issue. You're better off contacting Stripe support directly for help with integration problems: https://support.stripe.com/contact

To unblock you however, it looks like you have a typo. The key you're looking for is `idempotencyKey`, not `idempotencykey`. Notice the camelcase capitalisation. If you have a variable named `idempotencykey` which you defined earlier, then you'd pass it in explicitly like so:

```
{
  idempotencyKey: idempotencykey,
}
```
