### ISSUE TITLE
Remix Cloudflare App "globalThis.XMLHttpRequest is not a constructor" 

### ISSUE THREAD

**Issue by vonkoff** [stripe/stripe-node#1507]
### Describe the bug

```
import Stripe from 'stripe';

const secret = process.env.STRIPE_SECRET_KEY as string;

const stripe = new Stripe(secret, {
  apiVersion: '2022-08-01',
});
```
Simply this does not work. When I comment out these lines then I am able to run my Remix application that I am deploying through Cloudflare Pages. 

This is the error I get below. 

```
npm run dev                                                                                                                 

> dev
> remix build && run-p "dev:*"

Building Remix app in production mode...
Built in 348ms

> dev:wrangler
> cross-env NODE_ENV=development wrangler pages dev ./public


> dev:css
> npm run generate:css -- --watch


> dev:remix
> remix watch


> generate:css
> npx tailwindcss -i ./styles/tailwind.css -o ./app/styles/tailwind.css "--watch"

Watching Remix app in development mode...
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Compiling worker to "/var/folders/3l/zs3ghsw17731_bwjrw1tj7_m0000gn/T/functionsWorker-0.13010287351188832.js"...
Compiled Worker successfully.
💿 Built in 342ms
[pages:err] TypeError: globalThis.XMLHttpRequest is not a constructor
    at jp (/Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:6943:9)
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:6966:21
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:19:36
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:7130:22
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:19:36
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:7563:11
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:19:36
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:7571:11
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:20:30
    at /Users/vonkoff/GoodUnionJobs/cloudflare-pages-remix/functions/[[path]].js:7616:25

✘ [ERROR] Could not start Miniflare.
```

### To Reproduce

1. Create a payments.ts file in routes directory.
2. Add in the code (mentioned in the "Describe the bug").
3. Get the error above

### Expected behavior

To be able to setup a new Stripe constant from the Stripe Node Library. 

### OS

macOS 

### Node version

v18.3.0

### Library version

"stripe": "^10.0.0"

### API version

2022-08-01

**Comment by kamil-stripe** [comment]
Hi @vonkoff! Thank you for your report. I believe the error message is not related to the constant setup for the Stripe client. Was this application successfully deployed to CloudFlare Pages before? It is possible the error is caused custom environment that CloudFlare solutions use. Please see similar problem and possible mitigation in https://github.com/remix-run/remix/issues/2075.

In addition, I recommend forcing Stripe library to use `fetch` as the default HTTP client:
```javascript
const stripe = Stripe(<API_KEY>, {
  // This is needed to use the Fetch API rather than relying on the Node http
  // package.
  httpClient: Stripe.createFetchHttpClient(),
});
```

I am going to close the issue but please reopen it when necessary.

**Comment by kamil-stripe** [comment]
Thank you for a very detailed answer.

Regarding the first issue:
```
IntegrationError: In order to create a payment element, you must pass a valid PaymentIntent or SetupIntent client secret when creating the Elements group.

  e.g. stripe.elements({clientSecret: "{{CLIENT_SECRET}}"})
    at Qn (https://js.stripe.com/v3:1:216321)
    at ur (https://js.stripe.com/v3:1:223444)
    at new n (https://js.stripe.com/v3:1:227979)
    at e.<anonymous> (https://js.stripe.com/v3:1:231761)
    at e.create (https://js.stripe.com/v3:1:124023)
    at https://friendly-moonbeam-987f15.netlify.app/build/_shared/chunk-TCOU54UD.js:2:4156
    at Qf (https://friendly-moonbeam-987f15.netlify.app/build/entry.client-DAG6GRX3.js:7:1442)
    at Zf (https://friendly-moonbeam-987f15.netlify.app/build/entry.client-DAG6GRX3.js:9:5030)
    at L.unstable_runWithPriority (https://friendly-moonbeam-987f15.netlify.app/build/entry.client-DAG6GRX3.js:1:4096)
    at rn (https://friendly-moonbeam-987f15.netlify.app/build/entry.client-DAG6GRX3.js:5:38448)
```

Looking at the call stack, this seems to come from the stripe-js library, which is our front-end library hosted at https://github.com/stripe/stripe-js. The library does not utilize stripe-node at all.

Regarding second issue, I apologize my sample code was compressed more than it should. Please add `apiVersion` property (source code: https://github.com/stripe/stripe-node/blob/master/types/lib.d.ts#L72) like:
```js
const stripe = new Stripe(
  "sk_123",
  {
    apiVersion: "2022-08-01", // adjust this value if it is different than the API version used by your integration
    httpClient: Stripe.createFetchHttpClient(),
  }
);
```

**Comment by vonkoff** [comment]
Figured it out! 

Always something stupid...

In **pay.tsx** need to change the line from `options={{clientSecret: paymentIntent.clientSecret}}>` to  `options={{clientSecret: paymentIntent.client_secret}}>`
