### ISSUE TITLE
Error: The card object must have a value for 'number'.

### ISSUE THREAD

**Issue by brutalhonesty** [stripe/stripe-node#162]
Trying to generate a token so I can update a payment method on an account.
Stripe API version: ```2015-02-18```
node-stripe version: ```3.3.2```

Following: https://stripe.com/docs/api#create_card_token

Stacktrace:

```javascript
{ [Error: The card object must have a value for 'number'.]
  type: 'StripeCardError',
  stack: 'Error: The card object must have a value for \'number\'.\n    at Error._Error (/path/to/node_modules/stripe/lib/Error.js:12:17)\n    at Error.Constructor (/path/to/node_modules/stripe/lib/utils.js:113:13)\n    at Error.Constructor (/path/to/node_modules/stripe/lib/utils.js:113:13)\n    at Function.StripeError.generate (/path/to/node_modules/stripe/lib/Error.js:54:14)\n    at IncomingMessage.<anonymous> (/path/to/node_modules/stripe/lib/StripeResource.js:136:39)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:938:16\n    at process._tickDomainCallback (node.js:463:13)',
  rawType: 'card_error',
  code: 'invalid_number',
  param: 'number',
  message: 'The card object must have a value for \'number\'.',
  detail: undefined,
  raw:
   { message: 'The card object must have a value for \'number\'.',
     type: 'card_error',
     param: 'number',
     code: 'invalid_number' } }
```

Code:

```javascript
var stripe = require('stripe')('MY_SECRET');
stripe.setApiVersion('2015-02-18');
stripe.tokens.create({
  card: {
    number: '4012888888881881', // I've tried 424242424242424242 and 5555555555554444 as a string and int but still have the same error.
    exp_month: 12,
    exp_year: 2016,
    cvc: '999' // I've also tried 999 as an int.
  }
}, function(err, token) {
  if(err) {
    return callback(err);
  }
  return callback(null, token);
});
```

What can I do to generate the token?

**Comment by matthewarkin** [comment]
Hmm, I just upgraded to version 3.3.2 and I cant reproduce what you're seeing. 
This was my code: 

```javascript
var stripe = require('stripe')('sk_test_******************************');
stripe.setApiVersion('2015-02-18');
stripe.tokens.create({
  card: {
    number: '4012888888881881', // I've tried 424242424242424242 and 5555555555554444 as a string and int but still have the same error.
    exp_month: 12,
    exp_year: 2016,
    cvc: '999' // I've also tried 999 as an int.
  }
}, function(err, token) {
  if(err) {
    console.log(err);
  }
  console.log(token);
});
```

**Comment by brutalhonesty** [comment]
@matthewarkin Thanks for verifying for me. Was running some tests and it wasn't working the day of. When I went to test it again today, it seems to work properly. Not sure what the reason was.
