### ISSUE TITLE
Error: http.Agent is not a constructor

### ISSUE THREAD

**Issue by ChurikiTenna** [stripe/stripe-node#1638]
### Describe the bug

error on new Stripe

```
NodeHttpClient.js:6 Uncaught (in promise) TypeError: http.Agent is not a constructor
    at node_modules/stripe/lib/net/NodeHttpClient.js (NodeHttpClient.js:6:26)
    at __require2 (chunk-NNYXQWFV.js?v=619287ea:19:50)
    at Stripe.createNodeHttpClient (stripe.js:117:28)
    at new Stripe (stripe.js:89:44)
    at Object.initStripe (stripe.ts:12:28)
    at [lessonid].vue:189:5
    at runtime-core.esm-bundler.js:2723:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2697:29)
```

### To Reproduce

Call initStripe which is in following code snippets.

### Expected behavior

init Stripe successfully

### Code snippets

```JavaScript
import Stripe from 'stripe';

export const myStripe = ({
    userId
}: {
    userId: string
}) => {

    return {
        initStripe() {

            const stripe = new Stripe('<test key>', {
                apiVersion: '2022-11-15',
            });
        
            console.log("stripe",stripe)
        }
    }
}
```

### OS

macOS

### Node version

v17.0.0

### Library version

"stripe": "^11.3.0"

### API version

2022-11-15

**Comment by ChurikiTenna** [comment]
included this, then it worked.
httpClient: Stripe.createFetchHttpClient(),
