### ISSUE TITLE
Errors miss useful stack traces

### ISSUE THREAD

**Issue by oleg-codaio** [stripe/stripe-node#1707]
### Describe the bug

When using `stripe-node`, API errors seem to lose the full stack trace, making it hard to debug and find the code that triggered a particular error.

For instance, if I make a bad `customers.retrieve()` call (with an invalid customer ID), I get an error with the following stack trace:

```
No such customer: 'some_fake_id'
Error: No such customer: 'some_fake_id'
    at Function.generate (/somedir/node_modules/.pnpm/stripe@11.7.0/node_modules/stripe/lib/Error.js:38:24)
    at res.toJSON.then.StripeAPIError.message (/somedir/node_modules/.pnpm/stripe@11.7.0/node_modules/stripe/lib/RequestSender.js:104:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### To Reproduce

1. Trigger a failing Stripe network request, such as `customers.retrieve`
2. Observe the thrown error's stack trace

### Expected behavior

I'd expect the stack trace to contain the stack up to where the Stripe API request was made. Instead, I only get a partial internal stack.

### OS

macOS

### Node version

Node v16.17.1

### Library version

11.7.0

### API version

2022-11-15

### Additional context

See also: https://github.com/stripe/stripe-node/pull/118

**Comment by oleg-codaio** [comment]
To leave some notes on a proposed fix, I think the issue is that [async stack traces](https://v8.dev/docs/stack-trace-api#async-stack-traces) don't work due to use of `.then()` directly on Promises, instead of `await`:

https://github.com/stripe/stripe-node/blob/3dc8c54cf666bf5e4843b797542cc46252461560/src/RequestSender.ts#L144-L152

One solution is to save the original stack trace when the call is made via `new Error().stack`, then splat it into the stack of any thrown error later. This would have a small penalty of constructing stack traces on every Stripe request (which I'd imagine pales in comparison to the actual network request), so if that's a concern then this could be made optional too.
