### ISSUE TITLE
stripe.refunds.cancel doesn't work

### ISSUE THREAD

**Issue by gcobcqwe** [stripe/stripe-node#1771]
### Describe the bug

When I use the stripe.refunds.cancel function in test mode, it will throw a StripeInvalidRequestError: Charges must be refunded using the /v1/charges/{CHARGE_ID}/refunds endpoint.

Error message:
```
StripeInvalidRequestError: Charges must be refunded using the /v1/charges/{CHARGE_ID}/refunds endpoint.
    at Function.generate (/test_stripe/node_modules/stripe/cjs/Error.js:10:20)
    at res.toJSON.then.Error_js_1.StripeAPIError.message (/test_stripe/node_modules/stripe/cjs/RequestSender.js:105:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'StripeInvalidRequestError',
  raw: {
    message: 'Charges must be refunded using the /v1/charges/{CHARGE_ID}/refunds endpoint.',
    ...
    },
    statusCode: 400,
    ...
  },
  ...
}
```

### To Reproduce

1. npm install stripe
2. run stripe.refunds.cancel

### Expected behavior

The API function is available as described in the docs (https://stripe.com/docs/api/refunds/cancel?lang=node).

### Code snippets

```JavaScript
const stripe = require('stripe')('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');

const refund = await stripe.refunds.cancel(
  're_xxxxxxxxxxxxxxxxxxxxxxx'
);
```

### OS

CentOS

### Node version

Node v16.15.1

### Library version

stripe-node v12.2.0

### API version

2022-11-15

**Comment by pakrym-stripe** [comment]
Hi @gcobcqwe,

Github issues should be limited to bugs with the library itself. This is an integration question better directed to our support team: https://support.stripe.com/contact

**Comment by gcobcqwe** [comment]
@pakrym-stripe OK, got it. Thanks for your help.
