### ISSUE TITLE
[1]  ⨯ Error: Stripe: Argument "subscription_exposed_id" must be a string, but got: undefined (on API request to `GET /v1/subscriptions/{subscription_exposed_id}`)

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [stripe/stripe-node#1953]
### Describe the bug

Dear all,

I am just trying to understand how to stripe in my project. This is my `webhook` code

```js
import { headers } from "next/headers"
import Stripe from "stripe"

import { env } from "@/env.mjs"
import { db } from "@/lib/db"
import { stripe } from "@/lib/stripe"

export async function POST(req: Request) {
  const body = await req.text()
  const signature = headers().get("Stripe-Signature") as string

  let event: Stripe.Event

  try {
    event = stripe.webhooks.constructEvent(
      body,
      signature,
      env.STRIPE_WEBHOOK_SECRET
    )
  } catch (error) {
    return new Response(`Webhook Error: ${error.message}`, { status: 400 })
  }

  const session = event.data.object as Stripe.Checkout.Session

  console.log(event.type)

  if (event.type == "customer.created") {
    const subscription = await stripe.subscriptions.retrieve(
      session.subscription as string
    )

    console.log(subscription)
  }
  if (event.type === "customer.subscription.created") {
    // Retrieve the subscription details from Stripe.
    const subscription = await stripe.subscriptions.retrieve(
      session.subscription as string
    )

    // Update the user stripe into in our database.
    // Since this is the initial subscription, we need to update
    // the subscription id and customer id.
    await db.user.update({
      where: {
        id: session?.metadata?.userId,
      },
      data: {
        stripeSubscriptionId: subscription.id,
        stripeCustomerId: subscription.customer as string,
        stripePriceId: subscription.items.data[0].price.id,
        stripeCurrentPeriodEnd: new Date(
          subscription.current_period_end * 1000
        ),
      },
    })
  }

  if (event.type === "invoice.payment_succeeded") {
    // Retrieve the subscription details from Stripe.
    const subscription = await stripe.subscriptions.retrieve(
      session.subscription as string
    )

    // Update the price id and set the new period end.
    await db.user.update({
      where: {
        stripeSubscriptionId: subscription.id,
      },
      data: {
        stripePriceId: subscription.items.data[0].price.id,
        stripeCurrentPeriodEnd: new Date(
          subscription.current_period_end * 1000
        ),
      },
    })
  }

  return new Response(null, { status: 200 })
}

```

This is how I defined stripe

```js
import Stripe from "stripe"

import { env } from "@/env.mjs"

export const stripe = new Stripe(env.STRIPE_API_KEY, {
  apiVersion: "2022-11-15",
  typescript: true,
})
```

and I got this error 

```
1] charge.succeeded
[1]  ⨯ Error: Stripe: Argument "subscription_exposed_id" must be a string, but got: undefined (on API request to `GET /v1/subscriptions/{subscription_exposed_id}`)
[1]     at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:101:23)
[1]     at Array.reduce (<anonymous>)
[1]     at Constructor._getRequestOpts (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:98:35)
[1]     at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:145:29)
[1]     at new Promise (<anonymous>)
[1]     at Constructor._makeRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:141:16)
[1]     at Constructor.eval [as retrieve] (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeMethod.js:33:110)
[1]     at POST (webpack-internal:///(rsc)/./app/api/webhooks/stripe/route.ts:28:98)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async /Users/francescozuppichini/Documents/taxonomy-main/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.23.0_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62280
[1]  ⨯ Error: Stripe: Argument "subscription_exposed_id" must be a string, but got: undefined (on API request to `GET /v1/subscriptions/{subscription_exposed_id}`)
[1]     at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:101:23)
[1]     at Array.reduce (<anonymous>)
[1]     at Constructor._getRequestOpts (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:98:35)
[1]     at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:145:29)
[1]     at new Promise (<anonymous>)
[1]     at Constructor._makeRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeResource.js:141:16)
[1]     at Constructor.eval [as retrieve] (webpack-internal:///(rsc)/./node_modules/.pnpm/stripe@11.18.0/node_modules/stripe/esm/StripeMethod.js:33:110)
[1]     at POST (webpack-internal:///(rsc)/./app/api/webhooks/stripe/route.ts:33:98)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async /Users/francescozuppichini/Documents/taxonomy-main/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.23.0_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62280
```

When I

```bash
stripe trigger subscription.payment_succeeded
```

### To Reproduce

Follow my description

I have installed stripe using

`pnpm install stripe`

### Expected behavior

I guess I should not get an error

### OS

macOS

### Node version

v21.1.0

### Library version

1.18.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@FrancescoSaverioZuppichini Github issues are limited to features requests and bugs with the stripe-node library. Here this is purely an integration support question about your code better directed at our support team instead: https://support.stripe.com/contact

To unblock you, the problem is that you are calling the Retrieve Subscription [API](https://stripe.com/docs/api/subscriptions/retrieve) but are not passing a Subscription id `sub_123` and instead pass an empty/undefined variable. You can easily debug this yourself by adding logs to your code before/after calling our API and confirming what you are sending us and receiving back.
In your code, when you get `customer.created` as an Event, you expect to be able to use `session.subscription` which doesn't make sense at all in this case. This Event is about a **Customer** creation and the object it describes in `event.data.object` is a Customer [object](https://stripe.com/docs/api/customers/object) not a Checkout Session. What you want to do is follow the docs here instead: https://stripe.com/docs/payments/checkout/fulfill-orders

**Comment by FrancescoSaverioZuppichini** [comment]
> @FrancescoSaverioZuppichini Github issues are limited to features requests and bugs with the stripe-node library. Here this is purely an integration support question about your code better directed at our support team instead: https://support.stripe.com/contact
> 
> To unblock you, the problem is that you are calling the Retrieve Subscription [API](https://stripe.com/docs/api/subscriptions/retrieve) but are not passing a Subscription id `sub_123` and instead pass an empty/undefined variable. You can easily debug this yourself by adding logs to your code before/after calling our API and confirming what you are sending us and receiving back. In your code, when you get `customer.created` as an Event, you expect to be able to use `session.subscription` which doesn't make sense at all in this case. This Event is about a **Customer** creation and the object it describes in `event.data.object` is a Customer [object](https://stripe.com/docs/api/customers/object) not a Checkout Session. What you want to do is follow the docs here instead: https://stripe.com/docs/payments/checkout/fulfill-orders

Thanks a lot, will reach out to the support because I still don't get the full flow
