### ISSUE TITLE
 The header content contains invalid characters

### ISSUE THREAD

**Issue by nairicode** [stripe/stripe-node#246]
_http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at makeRequest (C:\Users\nairi\Desktop\ecommerce\node_modules\stripe\lib\Str
ipeResource.js:229:9)
    at C:\Users\nairi\Desktop\ecommerce\node_modules\stripe\lib\StripeResource.j
s:218:7
    at C:\Users\nairi\Desktop\ecommerce\node_modules\stripe\lib\stripe.js:151:7
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

----------------------------------------------------------------

code is work in cloud 9, but in my computer throw that error..
can help me ?

**Comment by remistr** [comment]
@nairicode I've seen that happen when your user-agent has invalid characters that Node.js doesn't support. You should modify the following script: https://github.com/stripe/stripe-node/blob/0d17f1b496e73a13b7e8542fdd2f2a41c515489f/lib/StripeResource.js#L204 to dump the headers so that you can narrow down which ones as a character that isn't supported by Node.js

**Comment by brandur** [comment]
I'm closing this issue out for now. Let us know if there's any new development here. Thanks!

**Comment by loic294** [comment]
I got the same isue. In am on Windows 10 an my account name contain a special character ( ï ) in it. 

I changed this line : https://github.com/stripe/stripe-node/blob/0d17f1b496e73a13b7e8542fdd2f2a41c515489f/lib/StripeResource.js#L212
to  
`headers['X-Stripe-Client-User-Agent'] = encodeURIComponent(cua); // Unofficial fix`

Now it works!

**Comment by brandur** [comment]
@loic294 Thanks for reporting and helping to narrow this down a bit! I added a fix in #259.
