### ISSUE TITLE
stripe.invoices.retrieveUpcoming(customerId) throws error rather than returning an empty response

### ISSUE THREAD

**Issue by bradsimantel** [stripe/stripe-node#301]
Using v4.6.0, when requesting upcoming invoices for a customer that doesn't have any upcoming invoices, you get an error rather than an empty response:

```
error:  Error: No upcoming invoices for customer: cus_xxxxxxxxxxx
    at Constructor._Error (/.../node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/.../node_modules/stripe/lib/utils.js:97:13)
    at Constructor (/.../node_modules/stripe/lib/utils.js:97:13)
    at Function.StripeError.generate (/.../node_modules/stripe/lib/Error.js:56:14)
    at IncomingMessage.<anonymous> (/.../node_modules/stripe/lib/StripeResource.js:137:39)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'd think it should behave more like the response for invoices:

```
{ object: 'list',
  count: 0,
  data: [],
  has_more: false,
  url: '/v1/invoices' }
```

**Comment by bradsimantel** [comment]
Ah sorry, I just checked with curl and it turns out this is the API's response:

```
{
  "error": {
    "type": "invalid_request_error",
    "message": "No upcoming invoices for customer: cus_A5F1aXoc9Dq9do"
  }
}
```

I'd still prefer if the API behaved differently, but it's not a client issue.

**Comment by brandur** [comment]
Ah, interesting.

@kjc-stripe Would you mind double-checking that this isn't a regression? Thanks!
