### ISSUE TITLE
Customer.create returns StripeError for card issue instead of StripeCardError 

### ISSUE THREAD

**Issue by stieg** [stripe/stripe-node#325]
### Expected Behavior
Failed call to customer create endpoint returns a StripeCardError error when it failed due to a card being declined.

### Actual Behavior
Failed call to customer create endpoint returned a generic error when it failed due to a card being declined.

### Details
Node: 6.3.1
Stripe Lib: 4.17.1
```
error: Unable to create customer: Error: Your card was declined.
    at Error._Error (/usr/src/afbeta/node_modules/stripe/lib/Error.js:12:17)
    at Error.Constructor (/usr/src/afbeta/node_modules/stripe/lib/utils.js:107:13)
    at Error.Constructor (/usr/src/afbeta/node_modules/stripe/lib/utils.js:107:13)
    at Function.StripeError.generate (/usr/src/afbeta/node_modules/stripe/lib/Error.js:54:14)
    at IncomingMessage.<anonymous> (/usr/src/afbeta/node_modules/stripe/lib/StripeResource.js:140:39)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ob-stripe** [comment]
Hi @stieg, this is expected. The proper way to handle errors with stripe-node is to check the error's `type` attribute, cf. https://stripe.com/docs/api/node#error_handling.

E.g. if you run this code:
```node
stripe.customers.create({
  source: "tok_chargeDeclined"
}, function(err, customer) {
  console.log(err.type);
});
```

`StripeCardError` would be printed to the console.

I'm going to close the issue, but please feel free to reply if you believe this is an actual bug in the library or if you can point to documentation that contradicts what I said!

**Comment by stieg** [comment]
Howdy @ob-stripe ,

   Ok.  Thanks for clarifying.  Will move over to checking type of `StripeErrors` instead of relying on the types you define internally like `StripeCardError`.  Of note there is no documentation in there that would prevent a user from doing the same thing again.  Perhaps throwing in a comment with a link you provided above would help going forward?  Cheers.
