### ISSUE TITLE
TypeError: Path must be a string. Received undefined when trying to create a customer

### ISSUE THREAD

**Issue by shawnostler** [stripe/stripe-node#359]
I am receiving this error and trace:

``` javascript
TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.join (path.js:1211:7)
      at Object.createResourcePathWithSymbols (node_modules/stripe/lib/StripeResource.js:75:23)
      at Object.<anonymous> (node_modules/stripe/lib/StripeMethod.js:79:25)
      at tryCatcher (node_modules/stripe/node_modules/bluebird/js/main/util.js:26:23)
```

When I am running this code: 

```javascript
var stripe = require('stripe')(process.env.STRIPE_SECRET_KEY || 'sk_test_****');

stripe.customers.create({
    description: 'account#' + account.id,
    source: account.stripe.token.id
}, {
      idempentency_key: action.id
})
.then(function (customer) {})
.catch(function (exception) {});

```
I am use node v6.10.3 and stripe-node v4.23.1 

I cannot seem to fix this or find any other reporting of the problem. Anyone have any ideas?

**Comment by shawnostler** [comment]
Sorry, spelling error. "idempotency_key" not "idempentency_key". Not a bug.
