### ISSUE TITLE
[Parse Cloud Code] Stripe.DEFAULT_TIMEOUT causes build error

### ISSUE THREAD

**Issue by coman3** [stripe/stripe-node#424]
Hey guys,
Absolutely love the the library! Long story short, this is a really easy fix.

Currently i have a parse-server setup, with a simple browserify build, building my source. This folder contains all of my "cloud code" for my parse server which is then built into `cloud/main.js` with all required libraries (stripe included). I am attempting to create a subscription, as a user executes a cloud code function but currently cant build when i have stripe required.

As Parse Server's cloud code isnt necessarily a node environment when executing the built source, requiring the http library fails. Error is as follows:
```
> btb-web-app@0.2.0 start <RedactedPath>\app
> npm run clean && npm run build && node index.js


> btb-web-app@0.2.0 clean <RedactedPath>\app
> rm -rf cloud


> btb-web-app@0.2.0 build <RedactedPath>\app
> browserify src/main.js --exclude buffer -o cloud/main.js

<RedactedPath>\app\cloud\main.js:42804
Stripe.DEFAULT_TIMEOUT = require('http').createServer().timeout;
                                         ^

TypeError: require(...).createServer is not a function
    at Object.<anonymous> (<RedactedPath>\app\cloud\main.js:42804:42)
    at Object.__dirname.338.../package.json (<RedactedPath>\app\cloud\main.js:43056:4)
    at s (<RedactedPath>\app\cloud\main.js:1:316)
    at <RedactedPath>\app\cloud\main.js:1:367
    at Object.__dirname.350../<functionName> (<RedactedPath>\app\cloud\main.js:44238:16)
    at s (<RedactedPath>\app\cloud\main.js:1:316)
    at e (<RedactedPath>\app\cloud\main.js:1:487)
    at Object.<anonymous> (<RedactedPath>\app\cloud\main.js:1:505)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
I seemed to fix this problem by changing `lib/stripe.js`:
``` js
// Use node's default timeout:
var http = require('http');
Stripe.DEFAULT_TIMEOUT = http.createServer ? http.createServer().timeout : 3200;
```

Firstly why do you enforce require('http'), and not just use a static or configurable timeout? Secondly, could my changes cause issues further down the line?

**Comment by jlomas-stripe** [comment]
@coman3 I think the difficulty here is in using browserify to build your server side code; that's less than ideal, because of things like this.

When you make that change in your local Stripe library, do things work otherwise?  Are you able to create a Test Customer, Subscription, etc using the Parse Cloud Code?

I do think that there's a risk here; we want to make sure that folks don't try to include this code client-side - and this failure makes that clear - but obviously it would be handy to be able to deploy the library to things like Parse, etc.

**Comment by ob-stripe** [comment]
I don't see too much of a problem with replacing the default timeout with a constant (it's what we do in all the other libraries), but I agree with @jlomas-stripe here: requiring `http` has the nice side-effect of ensuring users don't try to use the library in client-side code.

I know basically nothing about Parse. Is using browserify a requirement? It seems counter-intuitive to use a tool specifically designed for browser code to prepare backend code.

**Comment by jlomas-stripe** [comment]
@ob-stripe It's basically:

> The default entry point for your Cloud Code is at `./cloud/main.js` [0]

So you could just hand-roll that code, or you can have a build system assemble it for you.  `browserify` isn't really the ideal tool for this, since it's meant to 'browserify' node-style code, rather than build server-side code, but still.

I think a good solution here is probably hard-code the timeout (which makes sense, and apparently the [default is actually 12000 ms](https://nodejs.org/api/http.html#http_server_timeout), which ... seems long :) ) and then add in an explicit runtime test for the existence of `http` that throws a more descriptive error.

[0] http://docs.parseplatform.org/cloudcode/guide/

**Comment by coman3** [comment]
Yea, i fully brain farted yesterday. Realised that browserify was probably the worst option i could use to compile code... Sorry about that guys 😕

**Comment by ob-stripe** [comment]
@coman3 No worries :)
