### ISSUE TITLE
Can't update subscription.

### ISSUE THREAD

**Issue by allanchau** [stripe/stripe-node#524]
I am trying to update a subscription using:
```javascript
stripe.subscriptions.update("some subscription id", { cancel_at_period_end: true });
```

The docs https://stripe.com/docs/api/subscriptions/update say the `customer` parameter is required, but when I pass that is says
```json
{
    "type": "StripeInvalidRequestError",
    "stack": "Error: Received unknown parameter: customer\n    at Error._Error (/app/node_modules/stripe/lib/Error.js:12:17)\n    at Error.Constructor (/app/node_modules/stripe/lib/utils.js:134:13)\n    at Error.Constructor (/app/node_modules/stripe/lib/utils.js:134:13)\n    at Function.StripeError.generate (/app/node_modules/stripe/lib/Error.js:57:12)\n    at IncomingMessage.<anonymous> (/app/node_modules/stripe/lib/StripeResource.js:155:39)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at elasticAPMCallbackWrapper (/app/node_modules/elastic-apm-node/lib/instrumentation/index.js:159:27)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)",
    "rawType": "invalid_request_error",
    "code": "parameter_unknown",
    "param": "customer",
    "message": "Received unknown parameter: customer",
    "raw": {
        "code": "parameter_unknown",
        "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
        "message": "Received unknown parameter: customer",
        "param": "customer",
        "type": "invalid_request_error",
        "headers": {
            "server": "nginx",
            "date": "Mon, 26 Nov 2018 06:27:58 GMT",
            "content-type": "application/json",
            "content-length": "242",
            "connection": "close",
            "access-control-allow-credentials": "true",
            "access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
            "access-control-allow-origin": "*",
            "access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
            "access-control-max-age": "300",
            "cache-control": "no-cache, no-store",
            "request-id": "req_fvGjTp0fGFphW4",
            "stripe-version": "2018-11-08",
            "strict-transport-security": "max-age=31556926; includeSubDomains; preload"
        },
        "statusCode": 400,
        "requestId": "req_fvGjTp0fGFphW4"
    },
    "headers": {
        "server": "nginx",
        "date": "Mon, 26 Nov 2018 06:27:58 GMT",
        "content-type": "application/json",
        "content-length": "242",
        "connection": "close",
        "access-control-allow-credentials": "true",
        "access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
        "access-control-allow-origin": "*",
        "access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
        "access-control-max-age": "300",
        "cache-control": "no-cache, no-store",
        "request-id": "req_fvGjTp0fGFphW4",
        "stripe-version": "2018-11-08",
        "strict-transport-security": "max-age=31556926; includeSubDomains; preload"
    },
    "requestId": "req_fvGjTp0fGFphW4",
    "statusCode": 400
}
```

Without the customer, the request says it cannot find the subscription although it is in the dashboard (and working in the docs)?

```json
{
    "type": "StripeInvalidRequestError",
    "stack": "Error: No such subscription: sub_E1aw60PzckDfNj\n    at Error._Error (/app/node_modules/stripe/lib/Error.js:12:17)\n    at Error.Constructor (/app/node_modules/stripe/lib/utils.js:134:13)\n    at Error.Constructor (/app/node_modules/stripe/lib/utils.js:134:13)\n    at Function.StripeError.generate (/app/node_modules/stripe/lib/Error.js:57:12)\n    at IncomingMessage.<anonymous> (/app/node_modules/stripe/lib/StripeResource.js:155:39)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at elasticAPMCallbackWrapper (/app/node_modules/elastic-apm-node/lib/instrumentation/index.js:159:27)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)",
    "rawType": "invalid_request_error",
    "code": "resource_missing",
    "param": "id",
    "message": "No such subscription: sub_E1aw60PzckDfNj",
    "raw": {
        "code": "resource_missing",
        "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
        "message": "No such subscription: sub_E1aw60PzckDfNj",
        "param": "id",
        "type": "invalid_request_error",
        "headers": {
            "server": "nginx",
            "date": "Mon, 26 Nov 2018 06:18:00 GMT",
            "content-type": "application/json",
            "content-length": "238",
            "connection": "close",
            "access-control-allow-credentials": "true",
            "access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
            "access-control-allow-origin": "*",
            "access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
            "access-control-max-age": "300",
            "cache-control": "no-cache, no-store",
            "request-id": "req_ocY7Ve1WivWbD0",
            "stripe-version": "2018-11-08",
            "strict-transport-security": "max-age=31556926; includeSubDomains; preload"
        },
        "statusCode": 404,
        "requestId": "req_ocY7Ve1WivWbD0"
    },
    "headers": {
        "server": "nginx",
        "date": "Mon, 26 Nov 2018 06:18:00 GMT",
        "content-type": "application/json",
        "content-length": "238",
        "connection": "close",
        "access-control-allow-credentials": "true",
        "access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
        "access-control-allow-origin": "*",
        "access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
        "access-control-max-age": "300",
        "cache-control": "no-cache, no-store",
        "request-id": "req_ocY7Ve1WivWbD0",
        "stripe-version": "2018-11-08",
        "strict-transport-security": "max-age=31556926; includeSubDomains; preload"
    },
    "requestId": "req_ocY7Ve1WivWbD0",
    "statusCode": 404
}
```

**Comment by remi-stripe** [comment]
@allanchau The first subscription failed because you passed a customer id which is unexpected. The second one failed because the id of the subscription you passed (`sub_E1aw60PzckDfNj`) is already canceled so updating it now is impossible. It was canceled on November 23rd which you can confirm in the Dashboard directly!

If you have follow up questions, feel free to reach out to our support team here https://support.stripe.com/email
