### ISSUE TITLE
stripe.transfers.create error uncatchable?

### ISSUE THREAD

**Issue by lorensr** [stripe/stripe-node#577]
`stripe@6.7.0`

With the below code, when the error occurs (trying to transfer to a nonexistant destination), neither `after` nor `catching` are printed, and my server stops responding to requests.

```js
  try {
    console.log('before')
    const transfer = await stripe.transfers.create(...)
    console.log('after')    
  } catch (e) {
    console.log('catching')
  }
```

```
before
Bugsnag:  Encountered an uncaught error, terminating…
Error: The provided key 'sk_test_********************' does not have access to account 'acct_[redacted]' (or that account does not exist). Application access may have been revoked.
    at Constructor._Error (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/utils.js:134:13)
    at new Constructor (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/utils.js:134:13)
    at IncomingMessage.<anonymous> (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/StripeResource.js:166:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by paulasjes-stripe** [comment]
I'm unable to recreate using the following:

```
async function test() {
    try {
        const transfer = await stripe.transfers.create({
            amount: 1000,
            currency: 'usd',
            destination: 'act_123'
        });

        console.log('after');
    } catch(e) {
        console.log('catching');
    }
}

test();
```

`catching` prints as expected here, not printing `after` is expected as the previous awaited method errors. I think this might be something to do with `Bugsnag` terminating early for some reason.

I'm closing this as I don't think it has anything to do with the Stripe Node bindings. If you're still having problems please feel free to write in to Stripe support: https://support.stripe.com/contact

**Comment by lorensr** [comment]
Thanks, when I remove Bugsnag, the process no longer terminates, and the catch block runs. However, I also get these warnings—do you know what that's about? The statement is inside a try catch.

```
before
(node:6625) UnhandledPromiseRejectionWarning: Error: The provided key 'sk_test_********************EbcO' does not have access to account 'acct_...' (or that account does not exist). Application access may have been revoked.
    at Constructor._Error (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/utils.js:134:13)
    at new Constructor (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/utils.js:134:13)
    at IncomingMessage.<anonymous> (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/StripeResource.js:166:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:6625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6625) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
catching
{ Error: No such destination: acct_...
    at Constructor._Error (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/utils.js:134:13)
    at new Constructor (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/utils.js:134:13)
    at Function.StripeError.generate (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/Error.js:57:12)
    at IncomingMessage.<anonymous> (/Users/me/jobs/payment-portal/server/node_modules/stripe/lib/StripeResource.js:170:39)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  type: 'StripeInvalidRequestError',
```

**Comment by lorensr** [comment]
Nevermind, figured it out—I needed to also `await` where the function containing this code was called.
