### ISSUE TITLE
Error starting app

### ISSUE THREAD

**Issue by Taakn** [stripe/stripe-node#635]
Hello,

I am getting the following error (node 8.4, stripe 7.1.0):

```
/node_modules/stripe/lib/StripeResource.js:46
this.initialize(...arguments);
                ^^^
 
SyntaxError: Unexpected token ...
     at exports.runInThisContext (vm.js:53:16)
     at Module._compile (module.js:373:25)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/node_modules/stripe/lib/resources/Accounts.js:3:24)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
```

Thanks for your help

**Comment by rattrayalex-stripe** [comment]
Hi @Taakn – can you double check your Node version?
I see this with Node 8.4.0: 
```
➜  node --version
v8.4.0

➜  node
> console.log(...[1, 2])
1 2
undefined
```
Can you also share the line of your code that triggered this?

**Comment by Taakn** [comment]
Hi @rattrayalex-stripe thanks for your help. It's not a big deal since 6.36.0 is working but yes typing the lines you provided above gives the same result. The line that triggers it is:

`const stripe = require('stripe')(client_secret);`

**Comment by rattrayalex-stripe** [comment]
Hi @Taakn ,

Can you verify your node version? We no longer support Node 4, 5, or 7. 

eg;
```
console.log(process.version);
const stripe = require('stripe')(client_secret);
```

It [looks like](https://runkit.com/rattrayalex-stripe/5cf59556b975d2001a4eb03c) that line of code works in Node 8.

Sorry for the trouble – I'll take a look at throwing a more proactive, useful error message.

**Comment by Taakn** [comment]
Thank you for the time you took to resolve the situation, version is indeed outdated.
