### ISSUE TITLE
StripeConnectionError: An error occurred with our connection to Stripe.

### ISSUE THREAD

**Issue by malimccalla** [stripe/stripe-node#650]
Have been running into this issue during development. Sometimes everything works fine and other times I get this error

version: 7.20

I'm not sure if its a bug or a connectivity issue 

```sh
Get stripe account error { Error: An error occurred with our connection to Stripe.
    at Constructor._Error (/Users/tunebase/node_modules/stripe/lib/Error.js:12:16)
    at Constructor (/Users/tunebase/node_modules/stripe/lib/utils.js:164:17)
    at new Constructor (/Users/tunebase/node_modules/stripe/lib/utils.js:164:17)
    at /Users/tunebase/node_modules/stripe/lib/StripeResource.js:209:9
    at ClientRequest.req.on (/Users/tunebase/node_modules/stripe/lib/StripeResource.js:380:67)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at TLSSocket.socketOnEnd (_http_client.js:425:9)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
  type: 'StripeConnectionError',
  stack:
   'Error: An error occurred with our connection to Stripe.\n    at Constructor._Error (/Users/tunebase/node_modules/stripe/lib/Error.js:12:16)\n    at Constructor (/Users/tunebase/node_modules/stripe/lib/utils.js:164:17)\n    at new Constructor (/Users/tunebase/node_modules/stripe/lib/utils.js:164:17)\n    at /Users/tunebase/node_modules/stripe/lib/StripeResource.js:209:9\n    at ClientRequest.req.on (/Users/tunebase/node_modules/stripe/lib/StripeResource.js:380:67)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at TLSSocket.socketOnEnd (_http_client.js:425:9)\n    at TLSSocket.emit (events.js:187:15)\n    at TLSSocket.EventEmitter.emit (domain.js:442:20)',
  rawType: undefined,
  code: undefined,
  param: undefined,
  message: 'An error occurred with our connection to Stripe.',
  detail:
   { Error: socket hang up
       at createHangUpError (_http_client.js:322:15)
       at TLSSocket.socketOnEnd (_http_client.js:425:23)
       at TLSSocket.emit (events.js:187:15)
       at TLSSocket.EventEmitter.emit (domain.js:442:20)
       at endReadableNT (_stream_readable.js:1094:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' },
  raw:
   { message: 'An error occurred with our connection to Stripe.',
     detail:
      { Error: socket hang up
          at createHangUpError (_http_client.js:322:15)
          at TLSSocket.socketOnEnd (_http_client.js:425:23)
          at TLSSocket.emit (events.js:187:15)
          at TLSSocket.EventEmitter.emit (domain.js:442:20)
          at endReadableNT (_stream_readable.js:1094:12)
          at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } },
  headers: undefined,
  requestId: undefined,
  statusCode: undefined }
```

**Comment by brandur-stripe** [comment]
It looks at first glance like it's probably an intermittent connectivity problem. You could try [enabling automatic retries](https://github.com/stripe/stripe-node#network-retries) to give you some protection against this type of thing.

**Comment by malimccalla** [comment]
Thanks @brandur-stripe - I will add in some retries

**Comment by akhilakula** [comment]
iam facing same issue how did you solve it

**Comment by simonjcarr** [comment]
I had the same issue. It was because I had changed the rules on my firewall. If you run into the issue try disabling your firewall to see if that fixes it, then re-enable the firewall and add the correct rules.

**Comment by rbluethl** [comment]
Update: The call to create the customer within Stripe officially failed, but the customer was still created: https://dashboard.stripe.com/customers/cus_KYlog7Q08U98Ra

I will manually assign the Stripe customer to our organization and vice versa. We need to investigate why this happens/how it can be prevented in the future.

**Comment by notchuks** [comment]
> I had the same issue. It was because I had changed the rules on my firewall. If you run into the issue try disabling your firewall to see if that fixes it, then re-enable the firewall and add the correct rules.

Worked. Thanks.

**Comment by omawhite** [comment]
I'm also facing this issue while developing locally, enabling retries didn't help, I don't have my firewall enabled. It's happening on different network connections as well. I'm pretty lost.

**Comment by ilies-t** [comment]
We're having the same issue using a K8S cluster from Google Cloud Engine. I think it's the same problem as described here: https://stackoverflow.com/a/69888728

So we added this line (`httpClient: Stripe.createFetchHttpClient()`), and it worked perfectly!

```typescript
const stripe = Stripe('your_stripe_private_key', {
  httpClient: Stripe.createFetchHttpClient()
});
```
