### ISSUE TITLE
"The card_present source type with currency usd is not supported yet." error when creating a payment intent

### ISSUE THREAD

**Issue by dambusm** [stripe/stripe-node#702]
Hi, following the docs, I am attempting to create a payment intent on my server using the Reader Simulator. Running the simple example code from the docs:
```
(async function() {
  const intent = await stripe.paymentIntents.create({
    amount: 1000,
    currency: 'usd',
    payment_method_types: ['card_present'],
    capture_method: 'manual',
  });
})();
```

results in the following error being thrown:
```
> (node:29372) UnhandledPromiseRejectionWarning: Error: The card_present source type with currency usd is not supported yet.
    at Function.generate (/Users/willschaller/projects/personal/stripe-terminal-2/node_modules/stripe/lib/Error.js:49:16)
    at IncomingMessage.<anonymous> (/Users/willschaller/projects/personal/stripe-terminal-2/node_modules/stripe/lib/StripeResource.js:168:39)
    at Object.onceWrapper (events.js:298:28)
    at IncomingMessage.emit (events.js:214:15)
    at IncomingMessage.EventEmitter.emit (domain.js:499:23)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This also happens with the example backend (https://github.com/stripe/example-terminal-backend) and client app (https://github.com/stripe/stripe-terminal-js-demo).
Seems rather odd that usd would not be supported, so I'm guessing something else is going on. Any assistance would be appreciated!

**Comment by remi-stripe** [comment]
@dambusm Github issues should be limited to bugs in the library. It looks like you're having an API issue though that would likely require investigating the request in your account. My guess is that your account is in a country where Terminal is not yet supported and that's returning that error. I would recommend that you reach out to our support team directly and they can help quickly unbloc you: https://support.stripe.com/contact
