### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by bowtai** [stripe/stripe-node#710]
Node Version: `v10.16.2`
Stripe Node Version: `7.10.0`

When creating customer with invalid payment (i.e. `tok_cvcCheckFail`) results in a TypeError.

Here is my code:
```
let customer = await stripe.customers.create({
  description: config.PRODUCT,
  source: token.id, // tok_cvcCheckFail
  name: name,
  email: email,
  metadata: {
    user_id: userId, // needed for querying the users table
  },
});
```

I expect a 402 response but my program exits as soon as this is reached and my try/catch isn't able to recover from it.

Here is the error:
```
2019-10-15T19:34:02.166Z bc195bfe-00cd-4432-af3b-c9b938ec4521 TypeError: Cannot read property 'apply' of undefined
at StripeAPIError.StripeError (/var/task/bundle.js:69420:156)
at new StripeAPIError (/var/task/bundle.js:69513:261)
at IncomingMessage.<anonymous> (/var/task/bundle.js:68698:13)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Has the create customer API changed since version 7.1.0? Rolling back to this version yields the proper result.

**Comment by remi-stripe** [comment]
@bowtai  I tried similar code on 7.10.0 but not getting any error like yours. I get this:
```
node bug_repro.js
(node:28844) UnhandledPromiseRejectionWarning: Error: Your card's security code is incorrect.
    at Function.generate (.stripe-node-examples/node_modules/stripe/lib/Error.js:54:16)
    at IncomingMessage.res.once (.stripe-node-examples/node_modules/stripe/lib/StripeResource.js:168:39)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
(node:28844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Do you have a bit more details about the error/issue? Are you maybe using some third-party library to make the call(s) like DefinitelyTyped? Do you have a repro sample you could give me?

**Comment by bowtai** [comment]
Turns out webpack was the culprit in my case. I was using webpack v3.10.0 with babel-loader for transpiling. Once I removed webpack from the equation, everything worked properly.

**Comment by remi-stripe** [comment]
Glad you were able to figure it out. Flagging that usually when using webpack this means that you're trying to use stripe-node client-side in the browser which you should make sure to never do.  Creating a customer should be done server-side with your secret key!
