### ISSUE TITLE
StripeAuthenticationError when loading stripe secret from environment variables

### ISSUE THREAD

**Issue by jordykoppen** [stripe/stripe-node#950]
Hi all,

I'm currently working on a Stripe Checkout integration and I'm running into an issue when calling my api to create a Stripe session.

I'm using Next.js with API Routes and call my `create-stripe-session` endpoint to generate a session.
I load the Stripe Secret from my .env file create a stripe instance. However, by doing this I get an error from the following error from the Stripe API:
```
StripeAuthenticationError: Invalid API Key provided: "sk_test********************************M6F"
    at IncomingMessage.<anonymous> (********/node_modules/stripe/lib/StripeResource.js:169:21)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'StripeAuthenticationError',
  raw: {
    message: 'Invalid API Key provided: "sk_test********************************M6F"',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Wed, 08 Jul 2020 19:05:29 GMT',
      'content-type': 'application/json',
      'content-length': '148',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'www-authenticate': 'Bearer realm="Stripe"',
      'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
    },
    statusCode: 401,
    requestId: undefined
  },
  rawType: 'invalid_request_error',
  code: undefined,
  doc_url: undefined,
  param: undefined,
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Wed, 08 Jul 2020 19:05:29 GMT',
    'content-type': 'application/json',
    'content-length': '148',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'www-authenticate': 'Bearer realm="Stripe"',
    'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
  },
  requestId: undefined,
  statusCode: 401,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  setup_intent: undefined,
  source: undefined
}
```
Now when I copy the same exact secret from my .env and directly into my code, the request succeeds. As you can see in the error above, stripe does report I'm using a key which is the same one in my .env, but is marking it invalid.

The code for my API endpoint:
```
import { NextApiHandler } from 'next'
import Stripe from 'stripe'

const stripeKey = process.env.STRIPE_SECRET
const stripe = new Stripe(stripeKey, { apiVersion: '2020-03-02' })

const createStripeSession: NextApiHandler = async (req, res) => {
  if (req.method === 'POST') {
    const { lineItems } = JSON.parse(req.body)

    if (!lineItems) throw new Error('Empty body')

    const session = await stripe.checkout.sessions.create({
      billing_address_collection: 'required',
      payment_method_types: ['card', 'ideal'],
      line_items: lineItems,
      mode: 'payment',
      success_url:
        'http://localhost:3000/succes?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: 'http://localhost:3000/cancel',
    })

    res.json(session)
  }
}

export default createStripeSession
```

If necessary, I can setup a minimal repo to replicate the issue.

Node version: `13.14.0`
stripe version: `8.69.0`

**Comment by richardm-stripe** [comment]
Hi @jordykoppen, I think what is going on here is the api key you are sending has quotes around it. There's not normally quotes around the API key in this error message
```shell
$ curl https://api.stripe.com/customers   -u mykey:
{
  "error": {
    "message": "Invalid API Key provided: mykey",
    "type": "invalid_request_error"
  }
}
$ curl https://api.stripe.com/customers   -u \"mykey\":
{
  "error": {
    "message": "Invalid API Key provided: \"mykey\"",
    "type": "invalid_request_error"
  }
}
```

So I would check the quotation logic in whatever is setting your environment variable

**Comment by jordykoppen** [comment]
@richardm-stripe  Ah that totally slipped past me! I've fixed it now, thanks a lot 😃

**Comment by muhammadareeb01** [comment]
i've this issue when i applying the strip . i've checked my key is valid and correct 


Use `node --trace-deprecation ...` to show where the warning was created)
Error creating checkout session: [Error: Invalid API Key provided: sk_test_********************************************************************************************FdJp] {
  type: 'StripeAuthenticationError',
  rawType: 'invalid_request_error',
  code: undefined,
  param: undefined,
  detail: undefined,
  raw: [Object],
  headers: [Object],
  requestId: undefined,
  statusCode: 401,
  populate: [Function: populate]
}
